disabled_rules: 
  - trailing_whitespace
  - trailing_newline
opt_in_rules: 
  - empty_count
  - redundant_nil_coalescing
  - switch_case_on_newline
  - prohibited_super_call
  - private_outlet
  - overridden_super_call
  - operator_usage_whitespace
  - number_separator
  - implicitly_unwrapped_optional
  - force_unwrapping
  - first_where
  - fatal_error_message
  - explicit_init
  - conditional_returns_on_newline
  - closure_spacing
  - closure_end_indentation
included: 
  - CodeInputView

force_cast: warning
force_try: warning
large_tuple:
  warning: 3
  error: 4
line_length: 
  warning: 145
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1000
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
function_body_length:
  warning: 50
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - !str on
    - up
reporter: "xcode"