osx_image: xcode8.3
language: objective-c

env:
  global:
    - PROJECT=CodeInputView.xcodeproj
    - SCHEME=CodeInputView

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail 
- xcodebuild -scheme $SCHEME -project $PROJECT -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' build | xcpretty -c